### ISSUE TITLE
Failing build on master

### ISSUE THREAD

**Issue by pawptart** [allfourone/yermuv#8]
Hey guys, we now have our master branch failing build. Not sure what exactly caused that but we need to work on getting that fixed before moving too far forward.

The error in Travis is:
```/home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)```

**Comment by BigPhatNerd** [comment]
How do we run the Travis CI tests before creating a pull request or pushing?

**Comment by pawptart** [comment]
We can't, or at least not without a convoluted way to do it.

I think I know why our builds are failing and I am hoping to be able to resolve that tonight. For now we can ignore the issues with Travis as long as the other tests are passing and it works on local.

**Comment by pawptart** [comment]
This was fixed with a few changes to `.travis.yml`.
